version: "3.9"

services:
  web:
    container_name: web
    environment:
      - "DJANGO_SUPERUSER_USERNAME=admin"
      - "DJANGO_SUPERUSER_EMAIL=admin@email.com"
      - "DJANGO_SUPERUSER_PASSWORD=testpass123"
    build: .
    entrypoint: /code/docker_files/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: