version: "3.9"

services:
  web:
    container_name: web
    build: .
#    entrypoint: /code/docker_files/database_reset.sh
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: