app = "futsal-stat-track"
primary_region = "ams"
console_command = "/code/manage.py shell"

[build]
  dockerfile = "/code/docker_files/Dockerfile"
  ignorefile = "/code/docker_files/.dockerignore"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
