# Generated by Django 4.1.9 on 2023-07-14 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stat_track.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_home",
                    models.CharField(
                        choices=[
                            ("blue", "blue"),
                            ("orange", "orange"),
                            ("colors", "colors"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "team_away",
                    models.CharField(
                        choices=[
                            ("blue", "blue"),
                            ("orange", "orange"),
                            ("colors", "colors"),
                        ],
                        max_length=20,
                    ),
                ),
                ("home_goals", models.IntegerField(default=0)),
                ("away_goals", models.IntegerField(default=0)),
                ("match_in_matchday", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["matchday"],
            },
        ),
        migrations.CreateModel(
            name="MatchDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="Date of match",
                    ),
                ),
                ("match_counter", models.PositiveIntegerField(default=0)),
                (
                    "league",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stat_track.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=16)),
                ("last_name", models.CharField(max_length=16)),
                ("leagues", models.ManyToManyField(to="stat_track.league")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goals",
                    models.IntegerField(
                        default=0,
                        validators=[stat_track.models.Stat.positive_validator],
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stat_track.league",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stat_track.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stat_track.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchDayTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("blue", "blue"),
                            ("orange", "orange"),
                            ("colors", "colors"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stat_track.matchday",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stat_track.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="matchday",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="stat_track.matchday",
            ),
        ),
    ]
