# Generated by Django 4.1.9 on 2023-09-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stat_track", "0003_alter_matchday_date_delete_joinrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
