import uuid

from django.contrib.auth import get_user_model
from django.db import models

from stat_track.models import League

User = get_user_model()

class Report(models.Model):
    id = models.UUIDField(
        primary_key = True,
        default=uuid.uuid4,
        editable=False)
    league = models.ForeignKey(League, on_delete=models.CASCADE, related_name="reports")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reports")
    generated = models.DateField()
    pdf = models.FileField(upload_to='Reports', blank=True)
    temporary = models.BooleanField(default=False, editable=False) # First report generated by user should be TRUE, Used to determine if its a temp report

    def __str__(self):
        return f"rf-{self.id}"

    def save(self, *args, **kwargs):
        temp_reports_query = self.owner.reports.filter(temporary=True)
        if temp_reports_query and self not in temp_reports_query:
            self.temporary = False
        if not temp_reports_query:
            self.temporary = True
        super().save(*args, **kwargs)