# Generated by Django 4.2 on 2023-04-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, default='', to='stat_track.player'),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('team', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stat_track.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stat_track.player')),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
