# Generated by Django 4.2 on 2023-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0005_alter_stats_draws_alter_stats_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='draws',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='loses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
