# Generated by Django 4.2 on 2023-04-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0009_player_list_of_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='list_of_stats',
        ),
        migrations.AddField(
            model_name='player',
            name='list_of_stats',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stat_track.stats'),
        ),
    ]
