# Generated by Django 4.2 on 2023-04-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0010_remove_player_list_of_stats_player_list_of_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='list_of_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stat_track.stats'),
        ),
    ]
