# Generated by Django 4.2 on 2023-04-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0011_alter_player_list_of_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='player',
            new_name='player_obj',
        ),
        migrations.AlterField(
            model_name='player',
            name='list_of_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stat_track.stats'),
        ),
    ]
