# Generated by Django 4.2 on 2023-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0012_rename_player_stats_player_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='player_obj',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='list_of_stats',
        ),
        migrations.AddField(
            model_name='player',
            name='list_of_stats',
            field=models.ManyToManyField(related_name='players', to='stat_track.stats'),
        ),
    ]
