# Generated by Django 4.2 on 2023-04-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0013_rename_player_obj_stats_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='list_of_stats',
        ),
    ]
