# Generated by Django 4.2 on 2023-04-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0014_remove_player_list_of_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stat_track.match'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stat_track.player'),
        ),
    ]
