# Generated by Django 4.2 on 2023-04-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0016_alter_stats_match_alter_stats_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of match')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_away',
            field=models.CharField(choices=[('Blue', 'Team Blue'), ('Orange', 'Team Orange'), ('Colors', 'Team Colors')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_home',
            field=models.CharField(choices=[('Blue', 'Team Blue'), ('Orange', 'Team Orange'), ('Colors', 'Team Colors')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stat_track.matchday'),
        ),
    ]
