# Generated by Django 4.2 on 2023-04-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0017_matchday_remove_match_date_remove_match_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.CharField(choices=[('Blue', 'Team Blue'), ('Orange', 'Team Orange'), ('Colors', 'Team Colors')], default='Orange', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home',
            field=models.CharField(choices=[('Blue', 'Team Blue'), ('Orange', 'Team Orange'), ('Colors', 'Team Colors')], default='Blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=16),
        ),
    ]
