# Generated by Django 4.2 on 2023-04-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0019_alter_stats_options_remove_stats_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='match_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
