# Generated by Django 4.2 on 2023-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0022_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
