# Generated by Django 4.2 on 2023-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0023_rename_stats_stat_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='players',
            field=models.ManyToManyField(to='stat_track.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(default=0),
        ),
    ]
