# Generated by Django 4.2 on 2023-05-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0024_matchday_players_alter_match_away_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchday',
            name='players',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='team',
        ),
        migrations.CreateModel(
            name='MatchDayTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('Blue', 'Team Blue'), ('Orange', 'Team Orange'), ('Colors', 'Team Colors')], max_length=16)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stat_track.matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stat_track.player')),
            ],
        ),
    ]
