# Generated by Django 4.2 on 2023-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0025_remove_matchday_players_remove_stat_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.CharField(choices=[('blue', 'blue'), ('orange', 'orange'), ('colors', 'colors')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home',
            field=models.CharField(choices=[('blue', 'blue'), ('orange', 'orange'), ('colors', 'colors')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchdayticket',
            name='team',
            field=models.CharField(choices=[('blue', 'blue'), ('orange', 'orange'), ('colors', 'colors')], max_length=16),
        ),
    ]
