# Generated by Django 4.1.9 on 2023-06-21 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0026_alter_match_team_away_alter_match_team_home_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['matchday']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='matchday',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 21, 0), verbose_name='Date of match'),
        ),
    ]
