# Generated by Django 4.1.9 on 2023-06-24 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0027_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 21, 0), verbose_name='Date of match'),
        ),
    ]
