# Generated by Django 4.1.9 on 2023-07-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_track', '0029_alter_matchday_date_league_matchday_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leagues',
            field=models.ManyToManyField(to='stat_track.league'),
        ),
    ]
