# Generated by Django 4.1.9 on 2023-07-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stat_track", "0031_player_user_alter_league_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="leagues",
            field=models.ManyToManyField(blank=True, null=True, to="stat_track.league"),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
