# Generated by Django 4.1.9 on 2023-07-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stat_track", "0032_alter_player_leagues_alter_player_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stat_track.league",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="leagues",
            field=models.ManyToManyField(blank=True, to="stat_track.league"),
        ),
    ]
