# Generated by Django 4.1.9 on 2023-07-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stat_track", "0033_stat_league_alter_player_leagues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="leagues",
            field=models.ManyToManyField(to="stat_track.league"),
        ),
        migrations.AlterField(
            model_name="stat",
            name="league",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stat_track.league",
            ),
            preserve_default=False,
        ),
    ]
