# Generated by Django 4.1.9 on 2023-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="url",
            field=models.URLField(default="testurl"),
            preserve_default=False,
        ),
    ]
