# Generated by Django 4.1.9 on 2023-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf_generator", "0002_report_temporary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="temporary",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
